runtime: python310  # or your current Python version

entrypoint: gunicorn -b :$PORT app:app  # adjust 'main:app' to match your app's filename and variable

instance_class: F1  # free-tier eligible

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  idle_timeout: 10m

handlers:
  - url: /.*
    script: auto





